from .subviews.cookie_consent import *
from .subviews.index import *
from .subviews.create_dog import *
from .subviews.account import *
from .subviews.delete_account import *
from .subviews.dogs import *
from .subviews.dog import *
from .subviews.home import *
from .subviews.legal import *
from .subviews.story import *
