class DogActionEventType:
    FIND_MAGIC_BONE = 'FIND_MAGIC_BONE'
    FIND_FITNESS_COOKIE = 'FIND_FITNESS_COOKIE'
    FIND_TENNIS_BALL = 'FIND_TENNIS_BALL'
    MEET_ANOTHER_DOG = 'MEET_ANOTHER_DOG'
    GO_STORY = 'GO_STORY'
