# Generated by Django 3.0.4 on 2020-04-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Dog')),
            ],
            options={
                'db_table': 'dog_events',
            },
        ),
        migrations.AddIndex(
            model_name='dogevent',
            index=models.Index(fields=['-created_at'], name='dog_events_created_0eae5d_idx'),
        ),
    ]
