# Generated by Django 3.0.4 on 2020-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200407_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number_fitness_cookie',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='number_magic_bone',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='number_tennis_ball',
            field=models.BigIntegerField(default=1),
        ),
    ]
