# Generated by Django 3.0.4 on 2020-05-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200510_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('dog_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_from', to='main.Dog')),
                ('dog_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_to', to='main.Dog')),
            ],
            options={
                'db_table': 'dog_action_events',
            },
        ),
        migrations.AddIndex(
            model_name='dogactionevent',
            index=models.Index(fields=['dog_from', '-created_at'], name='dog_action__dog_fro_af7841_idx'),
        ),
    ]
