# Generated by Django 3.0.4 on 2020-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200523_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogactionevent',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
