# Generated by Django 3.0.4 on 2020-06-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dogactionevent_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('state', models.TextField(null=True)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Dog')),
            ],
            options={
                'db_table': 'stories',
            },
        ),
    ]
